export interface placeType {
  id: number;
  name: string;
  placesId: number;
  img: string;
  rating: number;
  location: string;
}
export const placesData: placeType[] = [
  {
    id: 1,
    name: "beach-1",
    placesId: 1,
    img: "beach1.jpg",
    rating: 4.5,
    location: "Myanmar",
  },
  {
    id: 2,
    name: "beach-2",
    placesId: 1,
    img: "beach2.jpg",
    rating: 4.5,
    location: "Thailand",
  },
  {
    id: 3,
    name: "beach-3",
    placesId: 1,
    img: "beach3.jpg",
    rating: 4.5,
    location: "Japan",
  },
  {
    id: 4,
    name: "beach-4",
    placesId: 1,
    img: "beach1.jpg",
    rating: 4.5,
    location: "Thailand",
  },
  {
    id: 5,
    name: "beach-5",
    placesId: 1,
    img: "beach3.jpg",
    rating: 4.5,
    location: "Japan",
  },
  {
    id: 6,
    name: "beach-6",
    placesId: 1,
    img: "beach2.jpg",
    rating: 4.5,
    location: "Myanmar",
  },
  {
    id: 7,
    name: "mountain-1",
    placesId: 2,
    img: "mount1.jpg",
    rating: 4.5,
    location: "Myanmar",
  },
  {
    id: 8,
    name: "mountain-2",
    placesId: 2,
    img: "mount2.jpg",
    rating: 4.5,
    location: "Japan",
  },
  {
    id: 9,
    name: "mountain-3",
    placesId: 2,
    img: "mount3.jpg",
    rating: 4.5,
    location: "Thailand",
  },
  {
    id: 10,
    name: "mountain-4",
    placesId: 2,
    img: "mount2.jpg",
    rating: 4.5,
    location: "Japan",
  },
  {
    id: 11,
    name: "mountain-5",
    placesId: 2,
    img: "mount1.jpg",
    rating: 4.5,
    location: "Myanmar",
  },
  {
    id: 12,
    name: "mountain-6",
    placesId: 2,
    img: "mount3.jpg",
    rating: 4.5,
    location: "Thailand",
  },
  {
    id: 13,
    name: "waterfall-1",
    placesId: 3,
    img: "wf1.jpg",
    rating: 4.5,
    location: "Japan",
  },
  {
    id: 14,
    name: "waterfall-2",
    placesId: 3,
    img: "wf2.jpg",
    rating: 4.5,
    location: "Myanmar",
  },
  {
    id: 15,
    name: "waterfall-3",
    placesId: 3,
    img: "wf3.jpg",
    rating: 4.5,
    location: "Thailand",
  },
  {
    id: 16,
    name: "waterfall-4",
    placesId: 3,
    img: "wf2.jpg",
    rating: 4.5,
    location: "Myanmar",
  },
  {
    id: 17,
    name: "waterfall-5",
    placesId: 3,
    img: "wf3.jpg",
    rating: 4.5,
    location: "Japan",
  },
  {
    id: 18,
    name: "waterfall-6",
    placesId: 3,
    img: "wf1.jpg",
    rating: 4.5,
    location: "Thailand",
  },
  {
    id: 19,
    name: "iceberg-1",
    placesId: 4,
    img: "ic1.jpg",
    rating: 4.5,
    location: "Myanmar",
  },
  {
    id: 20,
    name: "iceberg-2",
    placesId: 4,
    img: "ic2.jpg",
    rating: 4.5,
    location: "Thailand",
  },
  {
    id: 21,
    name: "iceberg-3",
    placesId: 4,
    img: "ic3.jpg",
    rating: 4.5,
    location: "Japan",
  },
  {
    id: 22,
    name: "iceberg-4",
    placesId: 4,
    img: "ic4.jpg",
    rating: 4.5,
    location: "Myanmar",
  },
  {
    id: 23,
    name: "iceberg-5",
    placesId: 4,
    img: "ic5.jpg",
    rating: 4.5,
    location: "Japan",
  },
  {
    id: 24,
    name: "iceberg-6",
    placesId: 4,
    img: "ic6.jpg",
    rating: 4.5,
    location: "Thailand",
  },
];
